---
title: GamerzOS' Network Settings
description: GamerzOS' optimised network settings
actions:
  - !cmd:
    command: '"GamerzOSDesktop\8. Troubleshooting\Network\Reset Network to GamerzOS Default.cmd" /silent'
    exeDir: true
    wait: true
