---
title: Configure Taskbar Pins
description: Configures taskbar pins for QoL, puts the browser first (if there is one) and Explorer next
actions:
    # PowerShell commands used:
    # [BitConverter]::ToString($(Get-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Taskband" -Name "FavoritesResolve").FavoritesResolve) -replace '-' | clip
    # [BitConverter]::ToString($(Get-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Taskband" -Name "Favorites").Favorites) -replace '-' | clip

  - !taskKill: {name: 'explorer'}

    # Config pins
  - !registryKey:
    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband'
  - !registryKey:
    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband'
    operation: add
  - !registryValue:
    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband'
    value: 'FavoritesVersion'
    data: '3'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband\AuxilliaryPins'
    value: 'MailPin'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband\AuxilliaryPins'
    value: 'CopilotPWAPin'
    data: '0'
    type: REG_DWORD
